using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace MESDataObject.Module.Vertiv
{
    public class ORDER_DETAIL_VT
    {
        public string OrderNumber { get; set; }
        public string OrderCreationDate { get; set; }
        public string OrderStatus { get; set; }
        public string OrderPriority { get; set; }
        public string CustomerName { get; set; }
        public string CustomerDescription { get; set; }
        public string CustomerDUNS { get; set; }
        public string CustomerDUNS4 { get; set; }
        public string CustomerTaxNumber { get; set; }
        public string CustomerAddressDescriptor { get; set; }
        public string CustomerAddress1 { get; set; }
        public string CustomerAddress2 { get; set; }
        public string CustomerAddress3 { get; set; }
        public string CustomerAddress4 { get; set; }
        public string CustomerAddress5 { get; set; }
        public string CustomerAddressCity { get; set; }
        public string CustomerAddressCounty { get; set; }
        public string CustomerAddressState { get; set; }
        public string CustomerAddressCountry { get; set; }
        public string CustomerAddressZip { get; set; }
        public string SupplierName { get; set; }
        public string SupplierDescription { get; set; }
        public string SupplierDUNS { get; set; }
        public string SupplierDUNS4 { get; set; }
        public string FlexAttrStringHeader16 { get; set; }
        public string FlexAttrStringHeader17 { get; set; }
        public string FlexAttrStringHeader18 { get; set; }
        public string FlexAttrStringHeader19 { get; set; }
        public string FlexAttrStringHeader20 { get; set; }
        public string FlexAttrDateLine6 { get; set; }
        public string FlexAttrDateLine7 { get; set; }
        public string FlexAttrDateLine8 { get; set; }
        public string FlexAttrDateLine9 { get; set; }
        public string FlexAttrDateLine10 { get; set; }
        public string FlexAttrFloatLine6 { get; set; }
        public string FlexAttrFloatLine7 { get; set; }
        public string FlexAttrFloatLine8 { get; set; }
        public string FlexAttrFloatLine9 { get; set; }
        public string FlexAttrFloatLine10 { get; set; }
        public string FlexAttrIntLine6 { get; set; }
        public string FlexAttrIntLine7 { get; set; }
        public string FlexAttrIntLine8 { get; set; }
        public string FlexAttrIntLine9 { get; set; }
        public string FlexAttrIntLine10 { get; set; }
        public string FlexAttrStringLine10 { get; set; }
        public string FlexAttrStringLine11 { get; set; }
        public string FlexAttrStringLine12 { get; set; }
        public string FlexAttrStringLine13 { get; set; }
        public string FlexAttrStringLine14 { get; set; }
        public string FlexAttrStringLine15 { get; set; }
        public string FlexAttrStringLine16 { get; set; }
        public string FlexAttrStringLine17 { get; set; }
        public string FlexAttrStringLine18 { get; set; }
        public string FlexAttrStringLine19 { get; set; }
        public string FlexAttrStringLine20 { get; set; }
        public string FlexAttrDateRequest6 { get; set; }
        public string FlexAttrDateRequest7 { get; set; }
        public string FlexAttrDateRequest8 { get; set; }
        public string FlexAttrDateRequest9 { get; set; }
        public string FlexAttrDateRequest10 { get; set; }
        public string FlexAttrFloatRequest6 { get; set; }
        public string FlexAttrIntRequest6 { get; set; }
        public string FlexAttrIntRequest7 { get; set; }
        public string FlexAttrIntRequest8 { get; set; }
        public string FlexAttrIntRequest9 { get; set; }
        public string FlexAttrIntRequest10 { get; set; }
        public string FlexAttrStringRequest10 { get; set; }
        public string FlexAttrStringRequest11 { get; set; }
        public string FlexAttrStringRequest12 { get; set; }
        public string FlexAttrStringRequest13 { get; set; }
        public string FlexAttrStringRequest14 { get; set; }
        public string FlexAttrStringRequest15 { get; set; }
        public string FlexAttrStringRequest16 { get; set; }
        public string FlexAttrStringRequest17 { get; set; }
        public string FlexAttrStringRequest18 { get; set; }
        public string FlexAttrStringRequest19 { get; set; }
        public string FlexAttrStringRequest20 { get; set; }
        public string FlexAttrDatePromise6 { get; set; }
        public string FlexAttrDatePromise7 { get; set; }
        public string FlexAttrDatePromise8 { get; set; }
        public string FlexAttrDatePromise9 { get; set; }
        public string FlexAttrDatePromise10 { get; set; }
        public string FlexAttrFloatPromise6 { get; set; }
        public string FlexAttrFloatPromise7 { get; set; }
        public string FlexAttrFloatPromise8 { get; set; }
        public string FlexAttrFloatPromise9 { get; set; }
        public string FlexAttrFloatPromise10 { get; set; }
        public string FlexAttrIntPromise6 { get; set; }
        public string FlexAttrIntPromise7 { get; set; }
        public string FlexAttrIntPromise8 { get; set; }
        public string FlexAttrIntPromise9 { get; set; }
        public string FlexAttrIntPromise10 { get; set; }
        public string FlexAttrStringPromise10 { get; set; }
        public string FlexAttrStringPromise11 { get; set; }
        public string FlexAttrStringPromise12 { get; set; }
        public string FlexAttrStringPromise13 { get; set; }
        public string FlexAttrStringPromise14 { get; set; }
        public string FlexAttrStringPromise15 { get; set; }
        public string FlexAttrStringPromise16 { get; set; }
        public string FlexAttrStringPromise17 { get; set; }
        public string FlexAttrStringPromise18 { get; set; }
        public string FlexAttrStringPromise19 { get; set; }
        public string FlexAttrStringPromise20 { get; set; }
        public string SupplierAddressDescriptor { get; set; }
        public string SupplierAddress1 { get; set; }
        public string SupplierAddress2 { get; set; }
        public string SupplierAddress3 { get; set; }
        public string SupplierAddress4 { get; set; }
        public string SupplierAddress5 { get; set; }
        public string SupplierAddressCity { get; set; }
        public string SupplierAddressCounty { get; set; }
        public string SupplierAddressState { get; set; }
        public string SupplierAddressCountry { get; set; }
        public string SupplierAddressZip { get; set; }
        public string BuyerCode { get; set; }
        public string BuyerContact { get; set; }
        public string BuyerName { get; set; }
        public string BuyerEmail { get; set; }
        public string SupplierEmail { get; set; }
        public string Freight { get; set; }
        public string PaymentTerms { get; set; }
        public string TotalOrderAmount { get; set; }
        public string InCoTerms { get; set; }
        public string HeaderNotesToCustomer { get; set; }
        public string HeaderNotesToSupplier { get; set; }
        public string BillTo { get; set; }
        public string BillToAddressDescriptor { get; set; }
        public string BillToAddress1 { get; set; }
        public string BillToAddress2 { get; set; }
        public string BillToAddress3 { get; set; }
        public string BillToAddress4 { get; set; }
        public string BillToAddress5 { get; set; }
        public string BillToAddressCity { get; set; }
        public string BillToAddressCounty { get; set; }
        public string BillToAddressState { get; set; }
        public string BillToAddressCountry { get; set; }
        public string BillToAddressZip { get; set; }
        public string RemitToAddressAddressDescriptor { get; set; }
        public string RemitToAddress1 { get; set; }
        public string RemitToAddress2 { get; set; }
        public string RemitToAddress3 { get; set; }
        public string RemitToAddress4 { get; set; }
        public string RemitToAddress5 { get; set; }
        public string RemitToAddressCity { get; set; }
        public string RemitToAddressCounty { get; set; }
        public string RemitToAddressState { get; set; }
        public string RemitToAddressCountry { get; set; }
        public string RemitToAddressZip { get; set; }
        public string FlexAttrStringHeader1 { get; set; }
        public string FlexAttrStringHeader2 { get; set; }
        public string FlexAttrStringHeader3 { get; set; }
        public string FlexAttrStringHeader4 { get; set; }
        public string FlexAttrStringHeader5 { get; set; }
        public string FlexAttrStringHeader6 { get; set; }
        public string FlexAttrStringHeader7 { get; set; }
        public string FlexAttrStringHeader8 { get; set; }
        public string FlexAttrStringHeader9 { get; set; }
        public string FlexAttrIntHeader1 { get; set; }
        public string FlexAttrIntHeader2 { get; set; }
        public string FlexAttrIntHeader3 { get; set; }
        public string FlexAttrIntHeader4 { get; set; }
        public string FlexAttrIntHeader5 { get; set; }
        public string FlexAttrFloatHeader1 { get; set; }
        public string FlexAttrFloatHeader2 { get; set; }
        public string FlexAttrFloatHeader3 { get; set; }
        public string FlexAttrFloatHeader4 { get; set; }
        public string FlexAttrFloatHeader5 { get; set; }
        public string FlexAttrDateHeader1 { get; set; }
        public string FlexAttrDateHeader2 { get; set; }
        public string FlexAttrDateHeader3 { get; set; }
        public string FlexAttrDateHeader4 { get; set; }
        public string FlexAttrDateHeader5 { get; set; }
        public string OrderLineId { get; set; }
        public string LineStatus { get; set; }
        public string CustomerItemName { get; set; }
        public string CustomerItemDescription { get; set; }
        public string SupplierItemName { get; set; }
        public string SupplierItemDescription { get; set; }
        public string UnitPrice { get; set; }
        public string BasisofUnitPrice { get; set; }
        public string Currency { get; set; }
        public string TotalLIAmount { get; set; }
        public string UnitOfMeasure { get; set; }
        public string LineNotesToCustomer { get; set; }
        public string LineNotesToSupplier { get; set; }
        public string FlexAttrStringLine1 { get; set; }
        public string FlexAttrStringLine2 { get; set; }
        public string FlexAttrStringLine3 { get; set; }
        public string FlexAttrStringLine4 { get; set; }
        public string FlexAttrStringLine5 { get; set; }
        public string FlexAttrStringLine6 { get; set; }
        public string FlexAttrStringLine7 { get; set; }
        public string FlexAttrStringLine8 { get; set; }
        public string FlexAttrStringLine9 { get; set; }
        public string FlexAttrIntLine1 { get; set; }
        public string FlexAttrIntLine2 { get; set; }
        public string FlexAttrIntLine3 { get; set; }
        public string FlexAttrIntLine4 { get; set; }
        public string FlexAttrIntLine5 { get; set; }
        public string FlexAttrFloatLine1 { get; set; }
        public string FlexAttrFloatLine2 { get; set; }
        public string FlexAttrFloatLine3 { get; set; }
        public string FlexAttrFloatLine4 { get; set; }
        public string FlexAttrFloatLine5 { get; set; }
        public string FlexAttrDateLine1 { get; set; }
        public string FlexAttrDateLine2 { get; set; }
        public string FlexAttrDateLine3 { get; set; }
        public string FlexAttrDateLine4 { get; set; }
        public string FlexAttrDateLine5 { get; set; }
        public string OrderRequestScheduleId { get; set; }
        public string RequestStatus { get; set; }
        public string Action { get; set; }
        public string RequestQty { get; set; }
        public string RequestDate { get; set; }
        public string RequestedShipDate { get; set; }
        public string Carrier { get; set; }
        public string CustomerSite { get; set; }
        public string ShipToAddressDescriptor { get; set; }
        public string ShipToAddress1 { get; set; }
        public string ShipToAddress2 { get; set; }
        public string ShipToAddress3 { get; set; }
        public string ShipToAddress4 { get; set; }
        public string ShipToAddress5 { get; set; }
        public string ShipToAddressCity { get; set; }
        public string ShipToAddressCounty { get; set; }
        public string ShipToAddressState { get; set; }
        public string ShipToAddressCountry { get; set; }
        public string ShipToAddressZip { get; set; }
        public string RefdOrderType { get; set; }
        public string RefdOrderNumber { get; set; }
        public string RefdOrderLineId { get; set; }
        public string RefdOrderScheduleId { get; set; }
        public string RefdOrderCustomer { get; set; }
        public string RefdOrderSupplier { get; set; }
        public string FlexAttrStringRequest1 { get; set; }
        public string FlexAttrStringRequest2 { get; set; }
        public string FlexAttrStringRequest3 { get; set; }
        public string FlexAttrStringRequest4 { get; set; }
        public string FlexAttrStringRequest5 { get; set; }
        public string FlexAttrStringRequest6 { get; set; }
        public string FlexAttrStringRequest7 { get; set; }
        public string FlexAttrStringRequest8 { get; set; }
        public string FlexAttrStringRequest9 { get; set; }
        public string FlexAttrIntRequest1 { get; set; }
        public string FlexAttrIntRequest2 { get; set; }
        public string FlexAttrIntRequest3 { get; set; }
        public string FlexAttrIntRequest4 { get; set; }
        public string FlexAttrIntRequest5 { get; set; }
        public string FlexAttrFloatRequest1 { get; set; }
        public string FlexAttrFloatRequest2 { get; set; }
        public string FlexAttrFloatRequest3 { get; set; }
        public string FlexAttrFloatRequest4 { get; set; }
        public string FlexAttrFloatRequest5 { get; set; }
        public string FlexAttrDateRequest1 { get; set; }
        public string FlexAttrDateRequest2 { get; set; }
        public string FlexAttrDateRequest3 { get; set; }
        public string FlexAttrDateRequest4 { get; set; }
        public string FlexAttrDateRequest5 { get; set; }
        public string OrderPromiseId { get; set; }
        public string PromiseQty { get; set; }
        public string PromiseDate { get; set; }
        public string PromisedShipmentDate { get; set; }
        public string SupplierSite { get; set; }
        public string ShipFromAddressDescriptor { get; set; }
        public string ShipFromAddress1 { get; set; }
        public string ShipFromAddress2 { get; set; }
        public string ShipFromAddress3 { get; set; }
        public string ShipFromAddress4 { get; set; }
        public string ShipFromAddress5 { get; set; }
        public string ShipFromAddressCity { get; set; }
        public string ShipFromAddressCounty { get; set; }
        public string ShipFromAddressState { get; set; }
        public string ShipFromAddressCountry { get; set; }
        public string ShipFromAddressZip { get; set; }
        public string FlexAttrStringPromise1 { get; set; }
        public string FlexAttrStringPromise2 { get; set; }
        public string FlexAttrStringPromise3 { get; set; }
        public string FlexAttrStringPromise4 { get; set; }
        public string FlexAttrStringPromise5 { get; set; }
        public string FlexAttrStringPromise6 { get; set; }
        public string FlexAttrStringPromise7 { get; set; }
        public string FlexAttrStringPromise8 { get; set; }
        public string FlexAttrStringPromise9 { get; set; }
        public string FlexAttrIntPromise1 { get; set; }
        public string FlexAttrIntPromise2 { get; set; }
        public string FlexAttrIntPromise3 { get; set; }
        public string FlexAttrIntPromise4 { get; set; }
        public string FlexAttrIntPromise5 { get; set; }
        public string FlexAttrFloatPromise1 { get; set; }
        public string FlexAttrFloatPromise2 { get; set; }
        public string FlexAttrFloatPromise3 { get; set; }
        public string FlexAttrFloatPromise4 { get; set; }
        public string FlexAttrFloatPromise5 { get; set; }
        public string FlexAttrDatePromise1 { get; set; }
        public string FlexAttrDatePromise2 { get; set; }
        public string FlexAttrDatePromise3 { get; set; }
        public string FlexAttrDatePromise4 { get; set; }
        public string FlexAttrDatePromise5 { get; set; }
        public string RevNumber { get; set; }
        public string ShipToCustomerName { get; set; }
        public string FlexAttrDateHeader6 { get; set; }
        public string FlexAttrDateHeader7 { get; set; }
        public string FlexAttrDateHeader8 { get; set; }
        public string FlexAttrDateHeader9 { get; set; }
        public string FlexAttrDateHeader10 { get; set; }
        public string FlexAttrFloatHeader6 { get; set; }
        public string FlexAttrFloatHeader7 { get; set; }
        public string FlexAttrFloatHeader8 { get; set; }
        public string FlexAttrFloatHeader9 { get; set; }
        public string FlexAttrFloatHeader10 { get; set; }
        public string FlexAttrIntHeader6 { get; set; }
        public string FlexAttrIntHeader7 { get; set; }
        public string FlexAttrIntHeader8 { get; set; }
        public string FlexAttrIntHeader9 { get; set; }
        public string FlexAttrIntHeader10 { get; set; }
        public string FlexAttrStringHeader10 { get; set; }
        public string FlexAttrStringHeader11 { get; set; }
        public string FlexAttrStringHeader12 { get; set; }
        public string FlexAttrStringHeader13 { get; set; }
        public string FlexAttrStringHeader14 { get; set; }
        public string FlexAttrStringHeader15 { get; set; }
    }
}
