using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace MESDataObject.Module.Vertiv
{
    public class SHIPMENT_DETAIL_VT
    {
        public string ShipmentId { get; set; }
        public string CustomerName { get; set; }
        public string CustomerDescription { get; set; }
        public string CustomerDUNS { get; set; }
        public string CustomerDUNS4 { get; set; }
        public string CustomerAddressDescriptor { get; set; }
        public string CustomerAddress1 { get; set; }
        public string CustomerAddress2 { get; set; }
        public string CustomerAddress3 { get; set; }
        public string CustomerAddress4 { get; set; }
        public string CustomerAddress5 { get; set; }
        public string CustomerAddressCity { get; set; }
        public string CustomerAddressCounty { get; set; }
        public string CustomerAddressState { get; set; }
        public string CustomerAddressCountry { get; set; }
        public string CustomerAddressZip { get; set; }
        public string SupplierName { get; set; }
        public string SupplierDescription { get; set; }
        public string SupplierDUNS { get; set; }
        public string SupplierDUNS4 { get; set; }
        public string SupplierAddressDescriptor { get; set; }
        public string SupplierAddress1 { get; set; }
        public string SupplierAddress2 { get; set; }
        public string SupplierAddress3 { get; set; }
        public string SupplierAddress4 { get; set; }
        public string SupplierAddress5 { get; set; }
        public string SupplierAddressCity { get; set; }
        public string SupplierAddressCounty { get; set; }
        public string SupplierAddressState { get; set; }
        public string SupplierAddressCountry { get; set; }
        public string SupplierAddressZip { get; set; }
        public string ShipmentCreationDate { get; set; }
        public string ShipmentCreatorCode { get; set; }
        public string ShipmentStatus { get; set; }
        public string ShipmentDate { get; set; }
        public string PlannedDeliveryDate { get; set; }
        public string ETAAtFinalSite { get; set; }
        public string LastKnownMilestone { get; set; }
        public string ArrivalAtLastKnownMilestone { get; set; }
        public string DepartureFromLastKnownMilestone { get; set; }
        public string CarrierName { get; set; }
        public string ShipmentMode { get; set; }
        public string WaybillNumber { get; set; }
        public string ShipmentDeliveryBOLNumber { get; set; }
        public string PackingSlipNumber { get; set; }
        public string CarrierReferenceNumber { get; set; }
        public string ShipperReferenceNumber { get; set; }
        public string ShipToLocationType { get; set; }
        public string CountryOfOrigin { get; set; }
        public string NumberOfPackages { get; set; }
        public string LicensePlateNumber { get; set; }
        public string ImporterOfRecordNumber { get; set; }
        public string ConsigneeNumber { get; set; }
        public string ForeignPortOfUnlading { get; set; }
        public string PlaceOfDelivery { get; set; }
        public string ShipToSite { get; set; }
        public string ShipToPartyName { get; set; }
        public string ShipToPartyDUNS { get; set; }
        public string ShipToAddressDescriptor { get; set; }
        public string ShipToAddress1 { get; set; }
        public string ShipToAddress2 { get; set; }
        public string ShipToAddress3 { get; set; }
        public string ShipToAddress4 { get; set; }
        public string ShipToAddress5 { get; set; }
        public string ShipToAddressCity { get; set; }
        public string ShipToAddressCounty { get; set; }
        public string ShipToAddressState { get; set; }
        public string ShipToAddressCountry { get; set; }
        public string ShipToAddressZip { get; set; }
        public string SupplierSiteName { get; set; }
        public string ShipFromAddressDescriptor { get; set; }
        public string ShipFromAddress1 { get; set; }
        public string ShipFromAddress2 { get; set; }
        public string ShipFromAddress3 { get; set; }
        public string ShipFromAddress4 { get; set; }
        public string ShipFromAddress5 { get; set; }
        public string ShipFromAddressCity { get; set; }
        public string ShipFromAddressCounty { get; set; }
        public string ShipFromAddressState { get; set; }
        public string ShipFromAddressCountry { get; set; }
        public string ShipFromAddressZip { get; set; }
        public string BillToName { get; set; }
        public string BillToAddressDescriptor { get; set; }
        public string BillToAddress1 { get; set; }
        public string BillToAddress2 { get; set; }
        public string BillToAddress3 { get; set; }
        public string BillToAddress4 { get; set; }
        public string BillToAddress5 { get; set; }
        public string BillToAddressCity { get; set; }
        public string BillToAddressCounty { get; set; }
        public string BillToAddressState { get; set; }
        public string BillToAddressCountry { get; set; }
        public string BillToAddressZip { get; set; }
        public string BookingPartyName { get; set; }
        public string BookingPartyDUNS { get; set; }
        public string BookingPartyAddressDescriptor { get; set; }
        public string BookingPartyAddress1 { get; set; }
        public string BookingPartyAddress2 { get; set; }
        public string BookingPartyAddress3 { get; set; }
        public string BookingPartyAddress4 { get; set; }
        public string BookingPartyAddress5 { get; set; }
        public string BookingPartyAddressCity { get; set; }
        public string BookingPartyAddressCounty { get; set; }
        public string BookingPartyAddressState { get; set; }
        public string BookingPartyAddressCountry { get; set; }
        public string BookingPartyAddressZip { get; set; }
        public string FlexAttrStringHeader1 { get; set; }
        public string FlexAttrStringHeader2 { get; set; }
        public string FlexAttrStringHeader3 { get; set; }
        public string FlexAttrStringHeader4 { get; set; }
        public string FlexAttrStringHeader5 { get; set; }
        public string FlexAttrStringHeader6 { get; set; }
        public string FlexAttrStringHeader7 { get; set; }
        public string FlexAttrStringHeader8 { get; set; }
        public string FlexAttrStringHeader9 { get; set; }
        public string FlexAttrIntHeader1 { get; set; }
        public string FlexAttrIntHeader2 { get; set; }
        public string FlexAttrIntHeader3 { get; set; }
        public string FlexAttrIntHeader4 { get; set; }
        public string FlexAttrIntHeader5 { get; set; }
        public string FlexAttrFloatHeader1 { get; set; }
        public string FlexAttrFloatHeader2 { get; set; }
        public string FlexAttrFloatHeader3 { get; set; }
        public string FlexAttrFloatHeader4 { get; set; }
        public string FlexAttrFloatHeader5 { get; set; }
        public string FlexAttrDateHeader1 { get; set; }
        public string FlexAttrDateHeader2 { get; set; }
        public string FlexAttrDateHeader3 { get; set; }
        public string FlexAttrDateHeader4 { get; set; }
        public string FlexAttrDateHeader5 { get; set; }
        public string ShipmentLineItemId { get; set; }
        public string ShipmentLineStatus { get; set; }
        public string Action { get; set; }
        public string CustomerItemName { get; set; }
        public string CustomerItemDescription { get; set; }
        public string SupplierItemName { get; set; }
        public string SupplierItemDescription { get; set; }
        public string BuyerCode { get; set; }
        public string ShippedQuantity { get; set; }
        public string UnitOfMeasure { get; set; }
        public string FreightCost { get; set; }
        public string Currency { get; set; }
        public string PackingSlipNumberLine { get; set; }
        public string LineNotesToCustomer { get; set; }
        public string NumberOfBoxes { get; set; }
        public string Weight { get; set; }
        public string CommodityHTS6 { get; set; }
        public string ManufacturerName { get; set; }
        public string ManufacturerDUNS { get; set; }
        public string ManufacturerAddressDescriptor { get; set; }
        public string ManufacturerAddress1 { get; set; }
        public string ManufacturerAddress2 { get; set; }
        public string ManufacturerAddress3 { get; set; }
        public string ManufacturerAddress4 { get; set; }
        public string ManufacturerAddress5 { get; set; }
        public string ManufacturerAddressCity { get; set; }
        public string ManufacturerAddressCounty { get; set; }
        public string ManufacturerAddressState { get; set; }
        public string ManufacturerAddressCountry { get; set; }
        public string ManufacturerAddressZip { get; set; }
        public string ContainerStuffingLocationName { get; set; }
        public string ContainerStuffingLocationDUNS { get; set; }
        public string ContainerStuffingLocationAddressDescriptor { get; set; }
        public string ContainerStuffingLocationAddress1 { get; set; }
        public string ContainerStuffingLocationAddress2 { get; set; }
        public string ContainerStuffingLocationAddress3 { get; set; }
        public string ContainerStuffingLocationAddress4 { get; set; }
        public string ContainerStuffingLocationAddress5 { get; set; }
        public string ContainerStuffingLocationAddressCity { get; set; }
        public string ContainerStuffingLocationAddressCounty { get; set; }
        public string ContainerStuffingLocationAddressState { get; set; }
        public string ContainerStuffingLocationAddressCountry { get; set; }
        public string ContainerStuffingLocationAddressZip { get; set; }
        public string ConsolidatorName { get; set; }
        public string ConsolidatorDUNS { get; set; }
        public string ConsolidatorAddressDescriptor { get; set; }
        public string ConsolidatorAddress1 { get; set; }
        public string ConsolidatorAddress2 { get; set; }
        public string ConsolidatorAddress3 { get; set; }
        public string ConsolidatorAddress4 { get; set; }
        public string ConsolidatorAddress5 { get; set; }
        public string ConsolidatorAddressCity { get; set; }
        public string ConsolidatorAddressCounty { get; set; }
        public string ConsolidatorAddressState { get; set; }
        public string ConsolidatorAddressCountry { get; set; }
        public string ConsolidatorAddressZip { get; set; }
        public string RefdOrderCustomer { get; set; }
        public string RefdOrderSupplier { get; set; }
        public string RefdOrderType { get; set; }
        public string RefdOrderNumber { get; set; }
        public string RefdOrderLineId { get; set; }
        public string RefdOrderScheduleId { get; set; }
        public string RefdOrderPromiseScheduleId { get; set; }
        public string FlexAttrStringLine1 { get; set; }
        public string FlexAttrStringLine2 { get; set; }
        public string FlexAttrStringLine3 { get; set; }
        public string FlexAttrStringLine4 { get; set; }
        public string FlexAttrStringLine5 { get; set; }
        public string FlexAttrStringLine6 { get; set; }
        public string FlexAttrStringLine7 { get; set; }
        public string FlexAttrStringLine8 { get; set; }
        public string FlexAttrStringLine9 { get; set; }
        public string FlexAttrIntLine1 { get; set; }
        public string FlexAttrIntLine2 { get; set; }
        public string FlexAttrIntLine3 { get; set; }
        public string FlexAttrIntLine4 { get; set; }
        public string FlexAttrIntLine5 { get; set; }
        public string FlexAttrFloatLine1 { get; set; }
        public string FlexAttrFloatLine2 { get; set; }
        public string FlexAttrFloatLine3 { get; set; }
        public string FlexAttrFloatLine4 { get; set; }
        public string FlexAttrFloatLine5 { get; set; }
        public string FlexAttrDateLine1 { get; set; }
        public string FlexAttrDateLine2 { get; set; }
        public string FlexAttrDateLine3 { get; set; }
        public string FlexAttrDateLine4 { get; set; }
        public string FlexAttrDateLine5 { get; set; }
        public string ShipToCustomerName { get; set; }
        public string ShipToCustomerDesc { get; set; }
        public string ShipToCustomerItemName { get; set; }
        public string ShipToCustomerItemDesc { get; set; }
        public string DropShipmentFlag { get; set; }
        public string FlexAttrDateHeader6 { get; set; }
        public string FlexAttrDateHeader7 { get; set; }
        public string FlexAttrDateHeader8 { get; set; }
        public string FlexAttrDateHeader9 { get; set; }
        public string FlexAttrDateHeader10 { get; set; }
        public string FlexAttrDateHeader11 { get; set; }
        public string FlexAttrDateHeader12 { get; set; }
        public string FlexAttrDateHeader13 { get; set; }
        public string FlexAttrDateHeader14 { get; set; }
        public string FlexAttrDateHeader15 { get; set; }
        public string FlexAttrFloatHeader6 { get; set; }
        public string FlexAttrFloatHeader7 { get; set; }
        public string FlexAttrFloatHeader8 { get; set; }
        public string FlexAttrFloatHeader9 { get; set; }
        public string FlexAttrFloatHeader10 { get; set; }
        public string FlexAttrIntHeader6 { get; set; }
        public string FlexAttrIntHeader7 { get; set; }
        public string FlexAttrIntHeader8 { get; set; }
        public string FlexAttrIntHeader9 { get; set; }
        public string FlexAttrIntHeader10 { get; set; }
        public string FlexAttrStringHeader10 { get; set; }
        public string FlexAttrStringHeader11 { get; set; }
        public string FlexAttrStringHeader12 { get; set; }
        public string FlexAttrStringHeader13 { get; set; }
        public string FlexAttrDateDelivery1 { get; set; }
        public string FlexAttrDateDelivery2 { get; set; }
        public string FlexAttrDateDelivery3 { get; set; }
        public string FlexAttrDateDelivery4 { get; set; }
        public string FlexAttrDateDelivery5 { get; set; }
        public string FlexAttrDateDelivery6 { get; set; }
        public string FlexAttrDateDelivery7 { get; set; }
        public string FlexAttrDateDelivery8 { get; set; }
        public string FlexAttrDateDelivery9 { get; set; }
        public string FlexAttrDateDelivery10 { get; set; }
        public string FlexAttrDateDelivery11 { get; set; }
        public string FlexAttrDateDelivery12 { get; set; }
        public string FlexAttrDateDelivery13 { get; set; }
        public string FlexAttrDateDelivery14 { get; set; }
        public string FlexAttrDateDelivery15 { get; set; }
        public string FlexAttrFloatDelivery1 { get; set; }
        public string FlexAttrFloatDelivery2 { get; set; }
        public string FlexAttrFloatDelivery3 { get; set; }
        public string FlexAttrFloatDelivery4 { get; set; }
        public string FlexAttrFloatDelivery5 { get; set; }
        public string FlexAttrFloatDelivery6 { get; set; }
        public string FlexAttrFloatDelivery7 { get; set; }
        public string FlexAttrFloatDelivery8 { get; set; }
        public string FlexAttrFloatDelivery9 { get; set; }
        public string FlexAttrFloatDelivery10 { get; set; }
        public string FlexAttrIntDelivery1 { get; set; }
        public string FlexAttrIntDelivery2 { get; set; }
        public string FlexAttrIntDelivery3 { get; set; }
        public string FlexAttrIntDelivery4 { get; set; }
        public string FlexAttrIntDelivery5 { get; set; }
        public string FlexAttrIntDelivery6 { get; set; }
        public string FlexAttrIntDelivery7 { get; set; }
        public string FlexAttrIntDelivery8 { get; set; }
        public string FlexAttrIntDelivery9 { get; set; }
        public string FlexAttrIntDelivery10 { get; set; }
        public string FlexAttrStringDelivery1 { get; set; }
        public string FlexAttrStringDelivery2 { get; set; }
        public string FlexAttrStringDelivery3 { get; set; }
        public string FlexAttrStringDelivery4 { get; set; }
        public string FlexAttrStringDelivery5 { get; set; }
        public string FlexAttrStringDelivery6 { get; set; }
        public string FlexAttrStringDelivery7 { get; set; }
        public string FlexAttrStringDelivery8 { get; set; }
        public string FlexAttrStringDelivery9 { get; set; }
        public string FlexAttrStringDelivery10 { get; set; }
        public string FlexAttrStringDelivery11 { get; set; }
        public string FlexAttrStringDelivery12 { get; set; }
        public string FlexAttrStringDelivery13 { get; set; }
        public string FlexAttrStringDelivery14 { get; set; }
        public string FlexAttrStringDelivery15 { get; set; }
        public string FlexAttrStringDelivery16 { get; set; }
        public string FlexAttrDateLine6 { get; set; }
        public string FlexAttrDateLine7 { get; set; }
        public string FlexAttrDateLine8 { get; set; }
        public string FlexAttrDateLine9 { get; set; }
        public string FlexAttrDateLine10 { get; set; }
        public string FlexAttrDateLine11 { get; set; }
        public string FlexAttrDateLine12 { get; set; }
        public string FlexAttrDateLine13 { get; set; }
        public string FlexAttrDateLine14 { get; set; }
        public string FlexAttrDateLine15 { get; set; }
        public string FlexAttrFloatLine6 { get; set; }
        public string FlexAttrFloatLine7 { get; set; }
        public string FlexAttrFloatLine8 { get; set; }
        public string FlexAttrFloatLine9 { get; set; }
        public string FlexAttrFloatLine10 { get; set; }
        public string FlexAttrIntLine6 { get; set; }
        public string FlexAttrIntLine7 { get; set; }
        public string FlexAttrIntLine8 { get; set; }
        public string FlexAttrIntLine9 { get; set; }
        public string FlexAttrIntLine10 { get; set; }
        public string FlexAttrStringLine10 { get; set; }
        public string FlexAttrStringLine11 { get; set; }
        public string FlexAttrStringLine12 { get; set; }
        public string FlexAttrStringLine13 { get; set; }
        public string FlexAttrStringLine14 { get; set; }
        public string FlexAttrStringLine15 { get; set; }
        public string FlexAttrStringLine16 { get; set; }
    }
}