//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MESStation.HateEmsGetDataService {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2634.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://mesplus.com/exception")]
    public partial class ServerException : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Nullable<ushort> scopeField;
        
        private string msgcodeField;
        
        private string msgcode1Field;
        
        private string msgField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public System.Nullable<ushort> scope {
            get {
                return this.scopeField;
            }
            set {
                this.scopeField = value;
                this.RaisePropertyChanged("scope");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string msgcode {
            get {
                return this.msgcodeField;
            }
            set {
                this.msgcodeField = value;
                this.RaisePropertyChanged("msgcode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("msgcode", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public string msgcode1 {
            get {
                return this.msgcode1Field;
            }
            set {
                this.msgcode1Field = value;
                this.RaisePropertyChanged("msgcode1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public string msg {
            get {
                return this.msgField;
            }
            set {
                this.msgField = value;
                this.RaisePropertyChanged("msg");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2634.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://mesplus.com/exception")]
    public partial class BugException : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string msgcodeField;
        
        private System.Nullable<ushort> scopeField;
        
        private string msgcode1Field;
        
        private string msgField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string msgcode {
            get {
                return this.msgcodeField;
            }
            set {
                this.msgcodeField = value;
                this.RaisePropertyChanged("msgcode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public System.Nullable<ushort> scope {
            get {
                return this.scopeField;
            }
            set {
                this.scopeField = value;
                this.RaisePropertyChanged("scope");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("msgcode", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public string msgcode1 {
            get {
                return this.msgcode1Field;
            }
            set {
                this.msgcode1Field = value;
                this.RaisePropertyChanged("msgcode1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public string msg {
            get {
                return this.msgField;
            }
            set {
                this.msgField = value;
                this.RaisePropertyChanged("msg");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2634.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://mesplus.com/exception")]
    public partial class TroubleException : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string msgcodeField;
        
        private serviceOut outField;
        
        private System.Nullable<ushort> scopeField;
        
        private string msgField;
        
        private string msgcode1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string msgcode {
            get {
                return this.msgcodeField;
            }
            set {
                this.msgcodeField = value;
                this.RaisePropertyChanged("msgcode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public serviceOut @out {
            get {
                return this.outField;
            }
            set {
                this.outField = value;
                this.RaisePropertyChanged("out");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public System.Nullable<ushort> scope {
            get {
                return this.scopeField;
            }
            set {
                this.scopeField = value;
                this.RaisePropertyChanged("scope");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public string msg {
            get {
                return this.msgField;
            }
            set {
                this.msgField = value;
                this.RaisePropertyChanged("msg");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("msgcode", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=4)]
        public string msgcode1 {
            get {
                return this.msgcode1Field;
            }
            set {
                this.msgcode1Field = value;
                this.RaisePropertyChanged("msgcode1");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(hateEmsGetDataServiceOut))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2634.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://mesplus.com/model")]
    public abstract partial class serviceOut : @out {
        
        private fieldmsg[] fieldmsgField;
        
        private fileinfo[] fileinfoField;
        
        private string msgField;
        
        private ushort msgcateField;
        
        private bool msgcateFieldSpecified;
        
        private string msgcodeField;
        
        private ushort statusvalueField;
        
        private bool statusvalueFieldSpecified;
        
        private int totalField;
        
        private bool totalFieldSpecified;
        
        private bool @__keepResultMsgField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("fieldmsg", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public fieldmsg[] fieldmsg {
            get {
                return this.fieldmsgField;
            }
            set {
                this.fieldmsgField = value;
                this.RaisePropertyChanged("fieldmsg");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("fileinfo", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public fileinfo[] fileinfo {
            get {
                return this.fileinfoField;
            }
            set {
                this.fileinfoField = value;
                this.RaisePropertyChanged("fileinfo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string msg {
            get {
                return this.msgField;
            }
            set {
                this.msgField = value;
                this.RaisePropertyChanged("msg");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public ushort msgcate {
            get {
                return this.msgcateField;
            }
            set {
                this.msgcateField = value;
                this.RaisePropertyChanged("msgcate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool msgcateSpecified {
            get {
                return this.msgcateFieldSpecified;
            }
            set {
                this.msgcateFieldSpecified = value;
                this.RaisePropertyChanged("msgcateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string msgcode {
            get {
                return this.msgcodeField;
            }
            set {
                this.msgcodeField = value;
                this.RaisePropertyChanged("msgcode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public ushort statusvalue {
            get {
                return this.statusvalueField;
            }
            set {
                this.statusvalueField = value;
                this.RaisePropertyChanged("statusvalue");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool statusvalueSpecified {
            get {
                return this.statusvalueFieldSpecified;
            }
            set {
                this.statusvalueFieldSpecified = value;
                this.RaisePropertyChanged("statusvalueSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public int total {
            get {
                return this.totalField;
            }
            set {
                this.totalField = value;
                this.RaisePropertyChanged("total");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool totalSpecified {
            get {
                return this.totalFieldSpecified;
            }
            set {
                this.totalFieldSpecified = value;
                this.RaisePropertyChanged("totalSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public bool @__keepResultMsg {
            get {
                return this.@__keepResultMsgField;
            }
            set {
                this.@__keepResultMsgField = value;
                this.RaisePropertyChanged("__keepResultMsg");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2634.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://mesplus.com/model")]
    public partial class fieldmsg : baseObject {
        
        private string nameField;
        
        private string textField;
        
        private string typeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
                this.RaisePropertyChanged("text");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("type");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(column))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(export))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(@in))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(serviceIn))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(hateEmsGetDataServiceIn))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(packList))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(trans))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(listOfTrans))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(fileinfo))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(fieldmsg))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(@out))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(serviceOut))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(hateEmsGetDataServiceOut))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2634.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://mesplus.com/model")]
    public abstract partial class baseObject : object, System.ComponentModel.INotifyPropertyChanged {
        
        private baseObjectEntry[] extendedFieldsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("entry", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public baseObjectEntry[] extendedFields {
            get {
                return this.extendedFieldsField;
            }
            set {
                this.extendedFieldsField = value;
                this.RaisePropertyChanged("extendedFields");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2634.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://mesplus.com/model")]
    public partial class baseObjectEntry : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string keyField;
        
        private object valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
                this.RaisePropertyChanged("key");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public object value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2634.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://mesplus.com/model")]
    public partial class column : baseObject {
        
        private column[] columnsField;
        
        private string dataIndexField;
        
        private string headerField;
        
        private int widthField;
        
        private bool widthFieldSpecified;
        
        private string xtypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("columns", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public column[] columns {
            get {
                return this.columnsField;
            }
            set {
                this.columnsField = value;
                this.RaisePropertyChanged("columns");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string dataIndex {
            get {
                return this.dataIndexField;
            }
            set {
                this.dataIndexField = value;
                this.RaisePropertyChanged("dataIndex");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string header {
            get {
                return this.headerField;
            }
            set {
                this.headerField = value;
                this.RaisePropertyChanged("header");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int width {
            get {
                return this.widthField;
            }
            set {
                this.widthField = value;
                this.RaisePropertyChanged("width");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool widthSpecified {
            get {
                return this.widthFieldSpecified;
            }
            set {
                this.widthFieldSpecified = value;
                this.RaisePropertyChanged("widthSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string xtype {
            get {
                return this.xtypeField;
            }
            set {
                this.xtypeField = value;
                this.RaisePropertyChanged("xtype");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2634.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://mesplus.com/model")]
    public partial class export : baseObject {
        
        private column[] columnsField;
        
        private string templatePathField;
        
        private string titleField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("columns", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public column[] columns {
            get {
                return this.columnsField;
            }
            set {
                this.columnsField = value;
                this.RaisePropertyChanged("columns");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string templatePath {
            get {
                return this.templatePathField;
            }
            set {
                this.templatePathField = value;
                this.RaisePropertyChanged("templatePath");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
                this.RaisePropertyChanged("title");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(serviceIn))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(hateEmsGetDataServiceIn))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2634.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://mesplus.com/model")]
    public abstract partial class @in : baseObject {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(hateEmsGetDataServiceIn))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2634.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://mesplus.com/model")]
    public abstract partial class serviceIn : @in {
        
        private export exportField;
        
        private string factoryField;
        
        private string[] fsDelFileIdField;
        
        private string[] fsTmpFileIdField;
        
        private ushort languageField;
        
        private bool languageFieldSpecified;
        
        private int limitField;
        
        private bool limitFieldSpecified;
        
        private int pageField;
        
        private bool pageFieldSpecified;
        
        private int pageIndexField;
        
        private bool pageIndexFieldSpecified;
        
        private int pageSizeField;
        
        private bool pageSizeFieldSpecified;
        
        private ushort procstepField;
        
        private bool procstepFieldSpecified;
        
        private int startField;
        
        private bool startFieldSpecified;
        
        private string useridField;
        
        private bool @__byPassField;
        
        private bool @__notCheckPrivilegeField;
        
        private bool @__rollbackField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public export export {
            get {
                return this.exportField;
            }
            set {
                this.exportField = value;
                this.RaisePropertyChanged("export");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string factory {
            get {
                return this.factoryField;
            }
            set {
                this.factoryField = value;
                this.RaisePropertyChanged("factory");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("fsDelFileId", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public string[] fsDelFileId {
            get {
                return this.fsDelFileIdField;
            }
            set {
                this.fsDelFileIdField = value;
                this.RaisePropertyChanged("fsDelFileId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("fsTmpFileId", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public string[] fsTmpFileId {
            get {
                return this.fsTmpFileIdField;
            }
            set {
                this.fsTmpFileIdField = value;
                this.RaisePropertyChanged("fsTmpFileId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public ushort language {
            get {
                return this.languageField;
            }
            set {
                this.languageField = value;
                this.RaisePropertyChanged("language");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool languageSpecified {
            get {
                return this.languageFieldSpecified;
            }
            set {
                this.languageFieldSpecified = value;
                this.RaisePropertyChanged("languageSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int limit {
            get {
                return this.limitField;
            }
            set {
                this.limitField = value;
                this.RaisePropertyChanged("limit");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool limitSpecified {
            get {
                return this.limitFieldSpecified;
            }
            set {
                this.limitFieldSpecified = value;
                this.RaisePropertyChanged("limitSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public int page {
            get {
                return this.pageField;
            }
            set {
                this.pageField = value;
                this.RaisePropertyChanged("page");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool pageSpecified {
            get {
                return this.pageFieldSpecified;
            }
            set {
                this.pageFieldSpecified = value;
                this.RaisePropertyChanged("pageSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public int pageIndex {
            get {
                return this.pageIndexField;
            }
            set {
                this.pageIndexField = value;
                this.RaisePropertyChanged("pageIndex");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool pageIndexSpecified {
            get {
                return this.pageIndexFieldSpecified;
            }
            set {
                this.pageIndexFieldSpecified = value;
                this.RaisePropertyChanged("pageIndexSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public int pageSize {
            get {
                return this.pageSizeField;
            }
            set {
                this.pageSizeField = value;
                this.RaisePropertyChanged("pageSize");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool pageSizeSpecified {
            get {
                return this.pageSizeFieldSpecified;
            }
            set {
                this.pageSizeFieldSpecified = value;
                this.RaisePropertyChanged("pageSizeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public ushort procstep {
            get {
                return this.procstepField;
            }
            set {
                this.procstepField = value;
                this.RaisePropertyChanged("procstep");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool procstepSpecified {
            get {
                return this.procstepFieldSpecified;
            }
            set {
                this.procstepFieldSpecified = value;
                this.RaisePropertyChanged("procstepSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public int start {
            get {
                return this.startField;
            }
            set {
                this.startField = value;
                this.RaisePropertyChanged("start");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool startSpecified {
            get {
                return this.startFieldSpecified;
            }
            set {
                this.startFieldSpecified = value;
                this.RaisePropertyChanged("startSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string userid {
            get {
                return this.useridField;
            }
            set {
                this.useridField = value;
                this.RaisePropertyChanged("userid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public bool @__byPass {
            get {
                return this.@__byPassField;
            }
            set {
                this.@__byPassField = value;
                this.RaisePropertyChanged("__byPass");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public bool @__notCheckPrivilege {
            get {
                return this.@__notCheckPrivilegeField;
            }
            set {
                this.@__notCheckPrivilegeField = value;
                this.RaisePropertyChanged("__notCheckPrivilege");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public bool @__rollback {
            get {
                return this.@__rollbackField;
            }
            set {
                this.@__rollbackField = value;
                this.RaisePropertyChanged("__rollback");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2634.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://mes.it.huawei.com/ws/HateEmsGetDataService")]
    public partial class hateEmsGetDataServiceIn : serviceIn {
        
        private string barcodeField;
        
        private string barcodeTypeField;
        
        private string beginTimeField;
        
        private string emsFactoryField;
        
        private string endTimeField;
        
        private string operationField;
        
        private string resultField;
        
        private string serviceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string barcode {
            get {
                return this.barcodeField;
            }
            set {
                this.barcodeField = value;
                this.RaisePropertyChanged("barcode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string barcodeType {
            get {
                return this.barcodeTypeField;
            }
            set {
                this.barcodeTypeField = value;
                this.RaisePropertyChanged("barcodeType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string beginTime {
            get {
                return this.beginTimeField;
            }
            set {
                this.beginTimeField = value;
                this.RaisePropertyChanged("beginTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string emsFactory {
            get {
                return this.emsFactoryField;
            }
            set {
                this.emsFactoryField = value;
                this.RaisePropertyChanged("emsFactory");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string endTime {
            get {
                return this.endTimeField;
            }
            set {
                this.endTimeField = value;
                this.RaisePropertyChanged("endTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string operation {
            get {
                return this.operationField;
            }
            set {
                this.operationField = value;
                this.RaisePropertyChanged("operation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("result");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string service {
            get {
                return this.serviceField;
            }
            set {
                this.serviceField = value;
                this.RaisePropertyChanged("service");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2634.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://mes.it.huawei.com/ws/HateEmsGetDataService")]
    public partial class packList : baseObject {
        
        private string[] pACKIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PACKID", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string[] PACKID {
            get {
                return this.pACKIDField;
            }
            set {
                this.pACKIDField = value;
                this.RaisePropertyChanged("PACKID");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2634.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://mes.it.huawei.com/ws/HateEmsGetDataService")]
    public partial class trans : baseObject {
        
        private string cENTERORDERIDField;
        
        private string eMSORDERIDField;
        
        private string mATIDField;
        
        private packList pACKLISTField;
        
        private string qTYField;
        
        private string sHIPPINGDATEField;
        
        private string tRANSIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string CENTERORDERID {
            get {
                return this.cENTERORDERIDField;
            }
            set {
                this.cENTERORDERIDField = value;
                this.RaisePropertyChanged("CENTERORDERID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string EMSORDERID {
            get {
                return this.eMSORDERIDField;
            }
            set {
                this.eMSORDERIDField = value;
                this.RaisePropertyChanged("EMSORDERID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string MATID {
            get {
                return this.mATIDField;
            }
            set {
                this.mATIDField = value;
                this.RaisePropertyChanged("MATID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public packList PACKLIST {
            get {
                return this.pACKLISTField;
            }
            set {
                this.pACKLISTField = value;
                this.RaisePropertyChanged("PACKLIST");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string QTY {
            get {
                return this.qTYField;
            }
            set {
                this.qTYField = value;
                this.RaisePropertyChanged("QTY");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string SHIPPINGDATE {
            get {
                return this.sHIPPINGDATEField;
            }
            set {
                this.sHIPPINGDATEField = value;
                this.RaisePropertyChanged("SHIPPINGDATE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string TRANSID {
            get {
                return this.tRANSIDField;
            }
            set {
                this.tRANSIDField = value;
                this.RaisePropertyChanged("TRANSID");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2634.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://mes.it.huawei.com/ws/HateEmsGetDataService")]
    public partial class listOfTrans : baseObject {
        
        private trans[] tRANSField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TRANS", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public trans[] TRANS {
            get {
                return this.tRANSField;
            }
            set {
                this.tRANSField = value;
                this.RaisePropertyChanged("TRANS");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2634.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://mesplus.com/model")]
    public partial class fileinfo : baseObject {
        
        private string fileIdField;
        
        private string fileNameField;
        
        private string fileSizeField;
        
        private string fileTypeField;
        
        private string groupIdField;
        
        private string paramNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string fileId {
            get {
                return this.fileIdField;
            }
            set {
                this.fileIdField = value;
                this.RaisePropertyChanged("fileId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string fileName {
            get {
                return this.fileNameField;
            }
            set {
                this.fileNameField = value;
                this.RaisePropertyChanged("fileName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string fileSize {
            get {
                return this.fileSizeField;
            }
            set {
                this.fileSizeField = value;
                this.RaisePropertyChanged("fileSize");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string fileType {
            get {
                return this.fileTypeField;
            }
            set {
                this.fileTypeField = value;
                this.RaisePropertyChanged("fileType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string groupId {
            get {
                return this.groupIdField;
            }
            set {
                this.groupIdField = value;
                this.RaisePropertyChanged("groupId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string paramName {
            get {
                return this.paramNameField;
            }
            set {
                this.paramNameField = value;
                this.RaisePropertyChanged("paramName");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(serviceOut))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(hateEmsGetDataServiceOut))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2634.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://mesplus.com/model")]
    public abstract partial class @out : baseObject {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2634.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://mes.it.huawei.com/ws/HateEmsGetDataService")]
    public partial class hateEmsGetDataServiceOut : serviceOut {
        
        private string barcodeField;
        
        private string emsMatIdField;
        
        private string emsOrderIdField;
        
        private string factoryField;
        
        private listOfTrans lISTOFTRANSField;
        
        private string lastTranCodeField;
        
        private string linkBarcodeField;
        
        private string lotTypeField;
        
        private string matIdField;
        
        private string operationField;
        
        private string preOperationField;
        
        private string reworkFlagField;
        
        private string workOrderField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string barcode {
            get {
                return this.barcodeField;
            }
            set {
                this.barcodeField = value;
                this.RaisePropertyChanged("barcode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string emsMatId {
            get {
                return this.emsMatIdField;
            }
            set {
                this.emsMatIdField = value;
                this.RaisePropertyChanged("emsMatId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string emsOrderId {
            get {
                return this.emsOrderIdField;
            }
            set {
                this.emsOrderIdField = value;
                this.RaisePropertyChanged("emsOrderId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string factory {
            get {
                return this.factoryField;
            }
            set {
                this.factoryField = value;
                this.RaisePropertyChanged("factory");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public listOfTrans LISTOFTRANS {
            get {
                return this.lISTOFTRANSField;
            }
            set {
                this.lISTOFTRANSField = value;
                this.RaisePropertyChanged("LISTOFTRANS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string lastTranCode {
            get {
                return this.lastTranCodeField;
            }
            set {
                this.lastTranCodeField = value;
                this.RaisePropertyChanged("lastTranCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string linkBarcode {
            get {
                return this.linkBarcodeField;
            }
            set {
                this.linkBarcodeField = value;
                this.RaisePropertyChanged("linkBarcode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string lotType {
            get {
                return this.lotTypeField;
            }
            set {
                this.lotTypeField = value;
                this.RaisePropertyChanged("lotType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string matId {
            get {
                return this.matIdField;
            }
            set {
                this.matIdField = value;
                this.RaisePropertyChanged("matId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string operation {
            get {
                return this.operationField;
            }
            set {
                this.operationField = value;
                this.RaisePropertyChanged("operation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string preOperation {
            get {
                return this.preOperationField;
            }
            set {
                this.preOperationField = value;
                this.RaisePropertyChanged("preOperation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string reworkFlag {
            get {
                return this.reworkFlagField;
            }
            set {
                this.reworkFlagField = value;
                this.RaisePropertyChanged("reworkFlag");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string workOrder {
            get {
                return this.workOrderField;
            }
            set {
                this.workOrderField = value;
                this.RaisePropertyChanged("workOrder");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2634.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://mesplus.com/exception")]
    public partial class ErrorException : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string msgcodeField;
        
        private serviceOut outField;
        
        private System.Nullable<ushort> scopeField;
        
        private string msgcode1Field;
        
        private string msgField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string msgcode {
            get {
                return this.msgcodeField;
            }
            set {
                this.msgcodeField = value;
                this.RaisePropertyChanged("msgcode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public serviceOut @out {
            get {
                return this.outField;
            }
            set {
                this.outField = value;
                this.RaisePropertyChanged("out");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public System.Nullable<ushort> scope {
            get {
                return this.scopeField;
            }
            set {
                this.scopeField = value;
                this.RaisePropertyChanged("scope");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("msgcode", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public string msgcode1 {
            get {
                return this.msgcode1Field;
            }
            set {
                this.msgcode1Field = value;
                this.RaisePropertyChanged("msgcode1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=4)]
        public string msg {
            get {
                return this.msgField;
            }
            set {
                this.msgField = value;
                this.RaisePropertyChanged("msg");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2634.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://mesplus.com/model")]
    public partial class header : object, System.ComponentModel.INotifyPropertyChanged {
        
        private headerEntry[] propsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("entry", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public headerEntry[] props {
            get {
                return this.propsField;
            }
            set {
                this.propsField = value;
                this.RaisePropertyChanged("props");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2634.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://mesplus.com/model")]
    public partial class headerEntry : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string keyField;
        
        private object valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
                this.RaisePropertyChanged("key");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public object value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2634.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://mes.it.huawei.com/ws/HateEmsGetDataService")]
    public partial class emsGetDataServiceResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private hateEmsGetDataServiceOut outField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public hateEmsGetDataServiceOut @out {
            get {
                return this.outField;
            }
            set {
                this.outField = value;
                this.RaisePropertyChanged("out");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2634.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://mes.it.huawei.com/ws/HateEmsGetDataService")]
    public partial class emsGetDataService : object, System.ComponentModel.INotifyPropertyChanged {
        
        private hateEmsGetDataServiceIn inField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public hateEmsGetDataServiceIn @in {
            get {
                return this.inField;
            }
            set {
                this.inField = value;
                this.RaisePropertyChanged("in");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://mes.it.huawei.com/ws/HateEmsGetDataService", ConfigurationName="HateEmsGetDataService.HateEmsGetDataService")]
    public interface HateEmsGetDataService {
        
        // CODEGEN: 操作 emsGetDataService 以后生成的消息协定不是 RPC，也不是换行文档。
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(MESStation.HateEmsGetDataService.ServerException), Action="", Name="ServerException", Namespace="http://mesplus.com/exception")]
        [System.ServiceModel.FaultContractAttribute(typeof(MESStation.HateEmsGetDataService.TroubleException), Action="", Name="TroubleException", Namespace="http://mesplus.com/exception")]
        [System.ServiceModel.FaultContractAttribute(typeof(MESStation.HateEmsGetDataService.BugException), Action="", Name="BugException", Namespace="http://mesplus.com/exception")]
        [System.ServiceModel.FaultContractAttribute(typeof(MESStation.HateEmsGetDataService.ErrorException), Action="", Name="ErrorException", Namespace="http://mesplus.com/exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BugException))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(TroubleException))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ErrorException))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(header))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(emsGetDataServiceResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(baseObject))]
        MESStation.HateEmsGetDataService.emsGetDataServiceResponse1 emsGetDataService(MESStation.HateEmsGetDataService.emsGetDataService1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<MESStation.HateEmsGetDataService.emsGetDataServiceResponse1> emsGetDataServiceAsync(MESStation.HateEmsGetDataService.emsGetDataService1 request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class emsGetDataService1 {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://mes.it.huawei.com/ws/HateEmsGetDataService")]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public MESStation.HateEmsGetDataService.header header;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://mes.it.huawei.com/ws/HateEmsGetDataService", Order=0)]
        public MESStation.HateEmsGetDataService.emsGetDataService emsGetDataService;
        
        public emsGetDataService1() {
        }
        
        public emsGetDataService1(MESStation.HateEmsGetDataService.header header, MESStation.HateEmsGetDataService.emsGetDataService emsGetDataService) {
            this.header = header;
            this.emsGetDataService = emsGetDataService;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="emsGetDataServiceResponse", WrapperNamespace="http://mes.it.huawei.com/ws/HateEmsGetDataService", IsWrapped=true)]
    public partial class emsGetDataServiceResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://mes.it.huawei.com/ws/HateEmsGetDataService", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public MESStation.HateEmsGetDataService.hateEmsGetDataServiceOut @out;
        
        public emsGetDataServiceResponse1() {
        }
        
        public emsGetDataServiceResponse1(MESStation.HateEmsGetDataService.hateEmsGetDataServiceOut @out) {
            this.@out = @out;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface HateEmsGetDataServiceChannel : MESStation.HateEmsGetDataService.HateEmsGetDataService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HateEmsGetDataServiceClient : System.ServiceModel.ClientBase<MESStation.HateEmsGetDataService.HateEmsGetDataService>, MESStation.HateEmsGetDataService.HateEmsGetDataService {
        
        public HateEmsGetDataServiceClient() {
        }
        
        public HateEmsGetDataServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HateEmsGetDataServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HateEmsGetDataServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HateEmsGetDataServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MESStation.HateEmsGetDataService.emsGetDataServiceResponse1 MESStation.HateEmsGetDataService.HateEmsGetDataService.emsGetDataService(MESStation.HateEmsGetDataService.emsGetDataService1 request) {
            return base.Channel.emsGetDataService(request);
        }
        
        public MESStation.HateEmsGetDataService.hateEmsGetDataServiceOut emsGetDataService(MESStation.HateEmsGetDataService.header header, MESStation.HateEmsGetDataService.emsGetDataService emsGetDataService1) {
            MESStation.HateEmsGetDataService.emsGetDataService1 inValue = new MESStation.HateEmsGetDataService.emsGetDataService1();
            inValue.header = header;
            inValue.emsGetDataService = emsGetDataService1;
            MESStation.HateEmsGetDataService.emsGetDataServiceResponse1 retVal = ((MESStation.HateEmsGetDataService.HateEmsGetDataService)(this)).emsGetDataService(inValue);
            return retVal.@out;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MESStation.HateEmsGetDataService.emsGetDataServiceResponse1> MESStation.HateEmsGetDataService.HateEmsGetDataService.emsGetDataServiceAsync(MESStation.HateEmsGetDataService.emsGetDataService1 request) {
            return base.Channel.emsGetDataServiceAsync(request);
        }
        
        public System.Threading.Tasks.Task<MESStation.HateEmsGetDataService.emsGetDataServiceResponse1> emsGetDataServiceAsync(MESStation.HateEmsGetDataService.header header, MESStation.HateEmsGetDataService.emsGetDataService emsGetDataService) {
            MESStation.HateEmsGetDataService.emsGetDataService1 inValue = new MESStation.HateEmsGetDataService.emsGetDataService1();
            inValue.header = header;
            inValue.emsGetDataService = emsGetDataService;
            return ((MESStation.HateEmsGetDataService.HateEmsGetDataService)(this)).emsGetDataServiceAsync(inValue);
        }
    }
}
