//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MESMailCenter.lotusNotesService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="lotusNotesService.LotusNotesServiceSoap")]
    public interface LotusNotesServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendNotesMail", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SendNotesMail(MESMailCenter.lotusNotesService.LotusMail Lmail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/test", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string test(string filename);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class LotusMail : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string[] mailToField;
        
        private string mailTitleField;
        
        private string mailAttachmentField;
        
        private string mailBodyField;
        
        private bool mailSaveField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public string[] MailTo {
            get {
                return this.mailToField;
            }
            set {
                this.mailToField = value;
                this.RaisePropertyChanged("MailTo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string MailTitle {
            get {
                return this.mailTitleField;
            }
            set {
                this.mailTitleField = value;
                this.RaisePropertyChanged("MailTitle");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string MailAttachment {
            get {
                return this.mailAttachmentField;
            }
            set {
                this.mailAttachmentField = value;
                this.RaisePropertyChanged("MailAttachment");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string MailBody {
            get {
                return this.mailBodyField;
            }
            set {
                this.mailBodyField = value;
                this.RaisePropertyChanged("MailBody");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public bool MailSave {
            get {
                return this.mailSaveField;
            }
            set {
                this.mailSaveField = value;
                this.RaisePropertyChanged("MailSave");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface LotusNotesServiceSoapChannel : MESMailCenter.lotusNotesService.LotusNotesServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LotusNotesServiceSoapClient : System.ServiceModel.ClientBase<MESMailCenter.lotusNotesService.LotusNotesServiceSoap>, MESMailCenter.lotusNotesService.LotusNotesServiceSoap {
        
        public LotusNotesServiceSoapClient() {
        }
        
        public LotusNotesServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LotusNotesServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LotusNotesServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LotusNotesServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string SendNotesMail(MESMailCenter.lotusNotesService.LotusMail Lmail) {
            return base.Channel.SendNotesMail(Lmail);
        }
        
        public string test(string filename) {
            return base.Channel.test(filename);
        }
    }
}
